# Generated by Django 4.2.13 on 2024-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0002_sharedfile_sharedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfolders',
            name='rootFolderid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
