# Generated by Django 4.2.13 on 2024-06-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0003_userfolders_rootfolderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfolders',
            name='rootFolderid',
        ),
    ]
