# Generated by Django 4.2.13 on 2024-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0005_userfolders_rootfolderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolders',
            name='rootFolderid',
            field=models.IntegerField(default=12),
        ),
    ]
