# Generated by Django 4.2.13 on 2024-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0006_alter_userfolders_rootfolderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolders',
            name='rootFolderid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
